Develop
MadAppGang/identifo.js pull request #2
Opened 2021-01-06 23:44 UTC by nikita-ks

2021-01-12 13:52 UTC, esimonov commented on src/UrlBuilder.ts
> +      + `?appId=${this.config?.appId}&scopes=${this.config?.scopes}&callbackUrl=${this.config?.redirectUri}/callback`;
I think you don't need the trailing `/callback` as that (if needed) is a part of redirectUri itself.

2021-01-12 13:52 UTC, esimonov commented on src/UrlBuilder.ts
> +      + `?appId=${this.config?.appId}&scopes=${this.config?.scopes}&callbackUrl=${this.config?.redirectUri}`;
Maybe that can be declared as a property (say, `urlParams` or something) and then reused throughout the methods createSignUpUrl, createSignInUrl, and createLogoutUrl.

2021-01-12 13:52 UTC, esimonov commented on src/constants.ts
> +export const jwtPattern = /^([a-zA-Z0-9_=]+)\.([a-zA-Z0-9_=]+)\.([a-zA-Z0-9_\-=]*$)/;
I'd call it `jwtRegex`, but I'm only sharing my thoughts.

2021-01-12 13:52 UTC, esimonov commented on src/index.ts
> +      this.isAuthenticated = false;
The method says it's for getting authentication status, but it's used for setting this status as well :)

2021-01-14 07:01 UTC, sokolovstas requested changes
И можно описать процесс как потестировать либу, тест приложение?

2021-01-14 07:01 UTC, sokolovstas commented on src/__tests__/UrlBuilder.test.ts
> +  test('should be defined and has methods', () => {
Надо бы добавить тесты на то что URL собираются правильно

2021-01-14 07:01 UTC, sokolovstas commented on package.json
> +    "build:dev": "webpack --watch",
--mode=development

У меня ребилд сработал в вотч моде

2021-01-14 07:01 UTC, sokolovstas commented on package.json
> +    "build:dev": "webpack --watch",
Еще вопрос почему не совпадает имя пакета и имя репы а так же путь куда билдятся файлы?
Обчно вроде билдят в filename: "dist/lib/identifo-react-js.js" наприрмер.

2021-01-14 07:01 UTC, sokolovstas commented on src/types/types.ts
> +  [propName: string]: any
тут наверное можно сделать number | string

2021-01-14 07:01 UTC, sokolovstas commented on src/tokenService.ts
> +  private tokenManager:TokenManager;
Если мы оставляем менеджер как менеджер то его нужно вынести классом и научить сохранять и получать из хранилища. То есть туда перейдут методы
1. get tokenFromStorage():string
2. window[this.tokenManager.storage].setItem(ACCESS_TOKEN_KEY, token);

Тогда получится логичная вещь что сервис просто просит менеджера положить или достать, не важно откуда.

2021-01-14 21:00 UTC, nikita-ks commented on src/types/types.ts
> +  [propName: string]: any
может же быть к примеру и boolean?

2021-01-14 21:01 UTC, nikita-ks commented on src/types/types.ts
> +  [propName: string]: any
> тут наверное можно сделать number | string
может же быть к примеру и boolean?

2021-01-18 10:32 UTC, sokolovstas commented on src/types/types.ts
> +  [propName: string]: any
В целом можно и any и исключение что бы правило не ругалось

2021-01-18 10:36 UTC, sokolovstas commented on src/__tests__/IdentifoAuth.test.ts
> +  test('should be rejected', () => expect(identifo.handleAuthentication()).rejects.toBeInstanceOf(Error));
Может добавим сюда тесты что бы проходила аунтификация? Проверить весь flow. Вроде бы должно получится подставить параметры во время теста и распарсить их. Валидную JWT какую нибудь сгенерировать на лету. Рефреш можно проверить во время теста сделав spyOn на Iframe

2021-01-22 08:16 UTC, sokolovstas approved these changes

2021-02-01 09:15 UTC, merged