remove async getToken, rename mathods, required params app id and authUrl, refactor urlbuilder
MadAppGang/identifo.js pull request #3
Opened 2021-03-16 07:07 UTC by nikita-ks

2021-03-16 12:33 UTC, erudenko requested changes

2021-03-16 12:33 UTC, erudenko commented on __tests__/UrlBuilder.test.ts
> +    authUrl: 'http://localhost:8081',
why not just use `url` ?

2021-03-16 12:33 UTC, erudenko commented on __tests__/UrlBuilder.test.ts
> +    returnTo: 'http://localhost:8081/returnTo',
what is the difference between `returnTo` and `callbackUrl`. I believe we need to improve naming here.

2021-03-18 07:01 UTC, sokolovstas approved these changes

2021-03-18 08:23 UTC, erudenko requested changes

2021-03-18 08:23 UTC, erudenko commented on __tests__/UrlBuilder.test.ts
> +    postLogoutRedirectUri: 'http://localhost:8081/returnTo',
not a good naming again on both sides, 
'postLogout` and `returnTo`

2021-03-18 08:29 UTC, erudenko approved these changes

2021-03-18 08:51 UTC, merged